module.exports = {
  appId: 'com.shawnstack.quickforge',
  productName: 'QuickForge',
  directories: {
    output: 'desktop-dist',
  },
  files: [
    'desktop/**',
    'server/**',
    'skills/**',
    'plugins/**',
    'vendor/**',
    'dist/**',
    'package.json',
    'LICENSE',
    'README.md',
  ],
  npmRebuild: false,
  asarUnpack: [
    '**/*.node',
    'vendor/node-pty/**',
    '**/node_modules/@vscode/os-proxy-resolver*/**',
    '**/node_modules/@vscode/windows-ca-certs/**',
  ],
  extraMetadata: {
    main: 'desktop/electron-main.mjs',
    desktopName: 'quickforge',
  },
  win: {
    target: 'nsis',
    icon: 'desktop/assets/icon.ico',
  },
  nsis: {
    oneClick: false,
    allowToChangeInstallationDirectory: true,
    createDesktopShortcut: true,
    createStartMenuShortcut: true,
    shortcutName: 'QuickForge',
    runAfterFinish: true,
    installerIcon: 'desktop/assets/icon.ico',
    uninstallerIcon: 'desktop/assets/icon.ico',
    include: 'desktop/installer.nsh',
  },
  mac: {
    target: 'dmg',
    icon: 'desktop/assets/icon.icns',
  },
  linux: {
    target: 'AppImage',
    icon: 'desktop/assets/icon.png',
    executableName: 'quickforge',
    category: 'Utility',
    syncDesktopName: true,
  },
}
